; -*- mode: lisp -*-
(in-package #:cl-user)
(defpackage #:dogatto-test/test-loader
  (:use #:cl)
  (:import-from #:dogatto-test/sample)
  (:import-from #:dogatto-test/controllers/health-controller)
  (:import-from #:dogatto-test/controllers/pages-controller)
  (:import-from #:dogatto-test/utils/password)
  (:import-from #:dogatto-test/utils/session)
  (:import-from :dogatto-test/models/user)
  (:import-from :dogatto-test/models/todo)
  (:import-from :dogatto-test/models/tag)
  (:import-from :dogatto-test/models/label)
  (:import-from :dogatto-test/controllers/auth-controller)
  (:import-from :dogatto-test/controllers/todos-controller)
  (:import-from :dogatto-test/controllers/tags-controller)
  (:import-from :dogatto-test/controllers/todo-tags-controller)
  (:import-from :dogatto-test/middleware/authentication))
(in-package #:dogatto-test/test-loader)

(dogatto/config/logger:initialize-logger :test)
