(format t "~%=== Loading clails ===~%")
(handler-case
    (progn
      (ql:quickload :clails :silent nil)
      (format t "~%Clails loaded successfully~%")
      (format t "~%Checking for base-controller package...~%")
      (if (find-package "CLAILS/CONTROLLER/BASE-CONTROLLER")
          (format t "Package exists!~%")
          (format t "Package DOES NOT exist!~%"))
      (format t "~%Available clails packages:~%")
      (dolist (pkg (list-all-packages))
        (when (search "CLAILS" (package-name pkg))
          (format t "  ~A~%" (package-name pkg)))))
  (error (e)
    (format t "Error loading clails: ~A~%" e)))
