# dogatto development Dockerfile
FROM fukamachi/sbcl:2.5.10

ENV BIND_ADDRESS="127.0.0.1" \
    PORT="5000" \
    SWANK_ADDRESS="127.0.0.1" \
    SWANK_PORT="4005" \
    PATH=${PATH}:/root/.roswell/bin:/qlot/.qlot/bin


RUN apt-get update && apt-get install -y \
  default-libmysqlclient-dev \
  libpq-dev \
  libsqlite3-dev \
  default-mysql-client \
  postgresql-client \
  sqlite3 \
  && rm -rf /var/lib/apt/lists/*

RUN ros install fukamachi/cl-dbi
RUN ros install tamurashingo/cl-dbi-connection-pool
RUN ros install tamurashingo/cl-batis
RUN ros install tamurashingo/getcmd


# install clails
ARG CLAILS_BRANCH=develop
RUN ros install tamurashingo/clails/${CLAILS_BRANCH}


RUN mkdir -p /app
WORKDIR /app

ENTRYPOINT /app/docker/run-dev.sh

