; -*- mode: lisp -*-
(in-package #:cl-user)
(defpackage #:dogatto/helpers/asset-helper
  (:use #:cl)
  (:import-from #:jonathan
                #:parse)
  (:export #:asset-path
           #:reload-manifest))

(in-package #:dogatto/helpers/asset-helper)

(defvar *manifest* nil
  "Cached Vite manifest data.")

(defun load-manifest ()
  "Loads the Vite manifest.json file.

   Reads the manifest.json generated by Vite build process.

   @return [hash-table] Manifest data as hash table
   @return [nil] If manifest file does not exist
   "
  (let ((manifest-path (merge-pathnames "public/assets/.vite/manifest.json"
                                        (asdf:system-source-directory :dogatto))))
    (when (probe-file manifest-path)
      (with-open-file (stream manifest-path :direction :input)
        (let ((json-string (make-string (file-length stream))))
          (read-sequence json-string stream)
          (parse json-string :as :hash-table))))))

(defun reload-manifest ()
  "Reloads the manifest from disk.

   Forces reloading of the manifest file, useful in development.

   @return [hash-table] Newly loaded manifest data
   "
  (setf *manifest* (load-manifest)))

(defun ensure-manifest ()
  "Ensures manifest is loaded.

   @return [hash-table] Manifest data
   "
  (unless *manifest*
    (setf *manifest* (load-manifest)))
  *manifest*)

(defun asset-path (path)
  "Returns the hashed asset path for the given path.

   Takes a path like \"/assets/javascript/index.js\" and returns the
   hashed version \"/assets/javascript/index-BsawTjHx.js\" by looking
   up the Vite manifest.

   @param path [string] Asset path (e.g., \"/assets/javascript/index.js\")
   @return [string] Hashed asset path (e.g., \"/assets/javascript/index-BsawTjHx.js\")
   @return [string] Original path if not found in manifest
   "
  (let ((manifest (ensure-manifest)))
    (if manifest
        ;; Extract the entry key from the path
        ;; "/assets/javascript/index.js" -> look up "index.html" in manifest
        (let ((entry (gethash "index.html" manifest)))
          (if entry
              (let ((file (gethash "file" entry)))
                (cond
                  ;; JavaScript file
                  ((search "javascript" path)
                   (concatenate 'string "/assets/" file))
                  ;; CSS file
                  ((search "css" path)
                   (let ((css-files (gethash "css" entry)))
                     (if (and css-files (> (length css-files) 0))
                         (concatenate 'string "/assets/" (elt css-files 0))
                         path)))
                  ;; Other files
                  (t path)))
              path))
        path)))
